- src/main/java/org/zanata/mt/api/dto/DocumentContent.java
- src/main/java/org/zanata/mt/api/dto/LocaleId.java
- src/main/java/org/zanata/mt/api/service/impl/DocumentContentTranslatorResourceImpl.java
- src/main/java/org/zanata/mt/backend/BackendLocaleCode.java
- src/main/java/org/zanata/mt/backend/ms/MicrosoftTranslatorBackend.java
- src/main/java/org/zanata/mt/backend/ms/internal/dto/MSLocaleCode.java
- src/main/java/org/zanata/mt/service/DocumentContentTranslatorService.java
- src/main/java/org/zanata/mt/service/PersistentTranslationService.java
- src/main/java/org/zanata/mt/servlet/APIResponseFilter.java
- src/main/java/org/zanata/mt/servlet/APISecurityFilter.java
- src/main/java/org/zanata/mt/servlet/JavaMelodyFilter.java
- src/main/resources/db/baseline.sql
- src/main/webapp/WEB-INF/web.xml
- src/test/java/org/zanata/mt/api/service/DocumentContentTranslatorResourceTest.java
- src/test/java/org/zanata/mt/backend/ms/MicrosoftTranslatorBackendTest.java
- src/test/java/org/zanata/mt/backend/ms/internal/dto/MSLocaleCodeTest.java
- src/test/java/org/zanata/mt/service/DocumentContentTranslatorServiceTest.java
- src/test/java/org/zanata/mt/servlet/APIResponseFilterTest.java
- src/test/java/org/zanata/mt/servlet/APISecurityFilterTest.java
- src/test/java/org/zanata/mt/servlet/JavaMelodyFilterTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-mt/4)
> feat: locale mapping for MS backend

- .editorconfig
- Jenkinsfile
https://zanata.atlassian.net/browse/ZNTA-1824
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-mt/8)
> ZNTA-1824 Jenkinsfile for zanata-mt

- src/main/java/org/zanata/mt/api/service/impl/DocumentContentTranslatorResourceImpl.java
- src/main/java/org/zanata/mt/model/Document.java
- src/main/java/org/zanata/mt/model/TextFlow.java
- src/main/java/org/zanata/mt/service/DocumentContentTranslatorService.java
- src/main/java/org/zanata/mt/service/PersistentTranslationService.java
- src/main/java/org/zanata/mt/util/DTOUtil.java
- src/main/resources/db/baseline.sql
- src/test/java/org/zanata/mt/api/service/DocumentContentTranslatorResourceTest.java
- src/test/java/org/zanata/mt/dao/TextFlowDAOTest.java
- src/test/java/org/zanata/mt/model/DocumentTest.java
- src/test/java/org/zanata/mt/model/TextFlowTargetTest.java
- src/test/java/org/zanata/mt/model/TextFlowTest.java
- src/test/java/org/zanata/mt/service/DocumentContentTranslatorServiceTest.java
- src/test/java/org/zanata/mt/service/PersistentTranslationServiceJPATest.java
- src/test/java/org/zanata/mt/service/PersistentTranslationServiceTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-mt/7)
> feat: Add many-to-many between Document and TextFlow

- src/main/java/org/zanata/mt/api/service/impl/DocumentContentTranslatorResourceImpl.java
- src/test/java/org/zanata/mt/api/service/DocumentContentTranslatorResourceTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-mt/9)
> fix: handle same source and target locale

- src/main/java/org/zanata/mt/api/service/DocumentContentTranslatorResource.java
https://zanata.atlassian.net/browse/ZNTA-1833
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-mt/10)
> fix: increase request limit to 10000 char

- src/main/java/org/zanata/mt/api/service/impl/DocumentContentTranslatorResourceImpl.java
- src/main/java/org/zanata/mt/model/TranslatableHTMLNode.java
- src/main/java/org/zanata/mt/service/DocumentContentTranslatorService.java
- src/main/java/org/zanata/mt/service/PersistentTranslationService.java
- src/main/java/org/zanata/mt/util/ArticleUtil.java
- src/main/java/org/zanata/mt/util/ExceptionUtil.java
- src/test/java/org/zanata/mt/api/service/DocumentContentTranslatorResourceTest.java
- src/test/java/org/zanata/mt/model/TranslatableHTMLNodeTest.java
- src/test/java/org/zanata/mt/service/DocumentContentTranslatorServiceTest.java
- src/test/java/org/zanata/mt/util/ArticleUtilTest.java
https://zanata.atlassian.net/browse/ZNTA-1833
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-mt/11)
> feat: put placeholder into non-translatable node

- pom.xml
- src/main/java/org/zanata/mt/api/service/impl/DocumentContentTranslatorResourceImpl.java
- src/main/java/org/zanata/mt/process/DocumentProcessKey.java
- src/main/java/org/zanata/mt/process/DocumentProcessManager.java
- src/test/java/org/zanata/mt/api/service/DocumentContentTranslatorResourceTest.java
- src/test/java/org/zanata/mt/process/DocumentProcessKeyTest.java
- src/test/java/org/zanata/mt/process/DocumentProcessManagerTest.java
- src/test/java/org/zanata/mt/process/DocumentProcessProviderTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-mt/12)
> Concurrency

- pom.xml
- src/main/java/org/zanata/mt/api/service/DocumentResource.java
- src/main/java/org/zanata/mt/backend/ms/MicrosoftTranslatorClient.java
- src/main/java/org/zanata/mt/service/DocumentContentTranslatorService.java
- src/main/java/org/zanata/mt/service/PersistentTranslationService.java
- src/main/java/org/zanata/mt/servlet/JavaMelodyFilter.java
- src/main/java/org/zanata/mt/util/SegmentString.java
- src/test/java/org/zanata/mt/service/DocumentContentTranslatorServiceTest.java
- src/test/java/org/zanata/mt/service/PersistentTranslationServiceJPATest.java
- src/test/java/org/zanata/mt/util/SegmentStringTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-mt/15)
> feat: segment long plain text

- Dockerfile
- pom.xml
- src/main/java/org/zanata/mt/api/dto/DocumentStatistics.java
- src/main/java/org/zanata/mt/api/dto/LocaleCode.java
- src/main/java/org/zanata/mt/api/dto/TranslationRequestStatistics.java
- src/main/java/org/zanata/mt/api/service/impl/DocumentResourceImpl.java
- src/main/java/org/zanata/mt/dao/TextFlowDAO.java
- src/main/java/org/zanata/mt/model/Document.java
- src/main/java/org/zanata/mt/model/TextFlow.java
- src/main/java/org/zanata/mt/model/TextFlowTarget.java
- src/main/java/org/zanata/mt/service/PersistentTranslationService.java
- src/main/java/org/zanata/mt/util/OkapiUtil.java
- src/main/resources/db/baseline.sql
- src/test/java/org/zanata/mt/api/dto/DocumentStatisticsTest.java
- src/test/java/org/zanata/mt/api/dto/TranslationRequestStatisticsTest.java
- src/test/java/org/zanata/mt/dao/TextFlowDAOTest.java
- src/test/java/org/zanata/mt/model/DocumentTest.java
- src/test/java/org/zanata/mt/model/TextFlowTargetTest.java
- src/test/java/org/zanata/mt/model/TextFlowTest.java
- src/test/java/org/zanata/mt/service/PersistentTranslationServiceJPATest.java
- src/test/java/org/zanata/mt/util/OkapiUtilTest.java
Refactor Document->TF to one-to-many relationship.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-mt/18)
> refactor: restructure document-TF relationship

- README.md
- pom.xml
- src/main/java/org/zanata/mt/api/APIConstant.java
- src/main/java/org/zanata/mt/api/service/impl/DocumentResourceImpl.java
- src/main/java/org/zanata/mt/backend/mock/MockTranslatorBackend.java
- src/main/java/org/zanata/mt/backend/ms/MicrosoftTranslatorBackend.java
- src/main/java/org/zanata/mt/model/BackendID.java
- src/main/java/org/zanata/mt/process/DocumentProcessManager.java
- src/main/java/org/zanata/mt/service/ConfigurationService.java
- src/main/java/org/zanata/mt/service/PersistentTranslationService.java
- src/main/java/org/zanata/mt/service/ZanataMTStartup.java
- src/main/resources/build.properties
- src/test/java/org/zanata/mt/api/service/DocumentResourceImplTest.java
- src/test/java/org/zanata/mt/backend/mock/MockTranslatorBackendTest.java
- src/test/java/org/zanata/mt/backend/ms/MicrosoftTranslatorBackendTest.java
- src/test/java/org/zanata/mt/backend/ms/MicrosoftTranslatorClientTest.java
- src/test/java/org/zanata/mt/service/ConfigurationServiceTest.java
- src/test/java/org/zanata/mt/service/PersistentTranslationServiceJPATest.java
- src/test/java/org/zanata/mt/service/PersistentTranslationServiceTest.java
- src/test/java/org/zanata/mt/service/ZanataMTStartupTest.java
https://zanata.atlassian.net/browse/ZNTAMT-2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-mt/21)
> feat: implement dev mode

- frontend/pom.xml
- pom.xml
- server/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-mt/23)
> Versions plugin

- .travis.yml
- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-mt/24)
> chore: add travis build

- Jenkinsfile
- README.md
chore: clean docker image, create github release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-mt/25)
> doc: fix typp in readme.md

- Jenkinsfile
- server/docker/Dockerfile-OPENSHIFT
chore: update eap version
chore: cleanup local docker images
chore: download cert in dockerfile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-mt/26)
> chore: download cert in dockerfile

- Jenkinsfile
chore: move prod input outside node
chore: use build version for prod deployment
chore: add milestone for build stage
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-mt/27)
> chore: move prod input outside node

- Jenkinsfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-mt/32)
> feat: upload war files during release

- Jenkinsfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-mt/35)
> fix(ZNTA-2234): Fix codecov url

- Jenkinsfile
Seem like the stash should be happen before deploy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-mt/36)
> fix postmerge ZNTA-2234

- Jenkinsfile
This might help with the review: https://github.com/zanata/zanata-mt/compare/ad25d1a0ff13ec1afac3e1b50ce28fd12ef3ab79...stash-after-build?w=1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-mt/37)
> Stash after build

- Jenkinsfile
Add parameters.
Also use readJson instead of jsonSlupers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-mt/40)
> ZNTA 2270 parameters

- Jenkinsfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-mt/41)
> correctParameters

- Jenkinsfile
Test envinject-api
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-mt/42)
> Check whether we are affected by JENKINS-28921

- .mvn/wrapper/maven-wrapper.properties
- .travis.yml
- Jenkinsfile
- pom.xml
- server/Dockerfile
- server/docker/zanata-mt-config.cli
- server/pom.xml
- server/src/main/java/org/zanata/mt/annotation/ClusteredCache.java
- server/src/main/java/org/zanata/mt/backend/google/GoogleCredential.java
- server/src/main/java/org/zanata/mt/process/DocumentProcessManager.java
- server/src/main/java/org/zanata/mt/service/ResourceProducer.java
- server/src/test/java/org/zanata/mt/api/service/DocumentResourceImplTest.java
- server/src/test/java/org/zanata/mt/integration/DocProcessManagerITCase.kt
- server/src/test/java/org/zanata/mt/integration/RestTest.kt
- server/src/test/java/org/zanata/mt/process/DocumentProcessManagerTest.java
- server/src/test/java/org/zanata/mt/service/ResourceProducerTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-mt/38)
> ZNTAMT-11 Infinispan lock

- Jenkinsfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-mt/43)
> ZNTA 2270 custom context

- Jenkinsfile
- server/docker/Dockerfile-OPENSHIFT
- server/src/main/java/org/zanata/mt/service/ResourceProducer.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-mt/44)
> fix: include ca cert in docker image

- server/docker/Dockerfile-OPENSHIFT
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-mt/45)
> use numeric uid for openshift

- server/Dockerfile
- server/docker/zanata-mt-config.cli
- server/src/main/webapp/WEB-INF/jboss-web.xml
- server/src/main/webapp/WEB-INF/web.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-mt/46)
> prepare cluster webapp session

- Jenkinsfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-mt/47)
> include intermediate CA certs

- Jenkinsfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-mt/50)
> feat(jenkins):env GITHUB_COMMIT_CONTEXT

- server/Dockerfile
https://zanata.atlassian.net/browse/ZNTAMT-18
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-mt/52)
> Retry 3 times for postgre downloading

- Jenkinsfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-mt/54)
> reduce build log from javax.net logging

- script/magpie_functional_test.py
Specification based functional tests in Python
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-mt/55)
> Magpie functional tests

- server/src/main/java/org/zanata/magpie/MTApplication.java
- server/src/main/java/org/zanata/magpie/api/dto/ApplicationInfo.java
- server/src/main/java/org/zanata/magpie/api/service/InfoResource.java
- server/src/main/java/org/zanata/magpie/api/service/impl/InfoResourceImpl.java
- server/src/main/java/org/zanata/magpie/service/MTStartup.java
- server/src/main/java/org/zanata/magpie/servlet/APISecurityFilter.java
- server/src/test/java/org/zanata/magpie/api/dto/ApplicationInfoTest.java
Specification based functional tests in Python
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zanata/zanata-mt/56)
> feat: info api

- rebuild.sh
- server/pom.xml
- server/src/main/java/org/zanata/magpie/service/MTStartup.java
JIRA: https://zanata.atlassian.net/browse/ZNTAMT-20
> fix(ZNTAMT-20): Allow user setting of default provider

- README.md
- common/pom.xml
- common/src/main/java/org/zanata/magpie/api/APIConstant.java
- common/src/main/java/org/zanata/magpie/api/dto/APIResponse.java
- common/src/main/java/org/zanata/magpie/api/dto/AccountDto.java
- common/src/main/java/org/zanata/magpie/api/dto/ApplicationInfo.java
- common/src/main/java/org/zanata/magpie/api/dto/DocumentContent.java
- common/src/main/java/org/zanata/magpie/api/dto/DocumentStatistics.java
- common/src/main/java/org/zanata/magpie/api/dto/Locale.java
- common/src/main/java/org/zanata/magpie/api/dto/TranslationRequestStatistics.java
- common/src/main/java/org/zanata/magpie/api/dto/TypeString.java
- mt-data/pom.xml
- mt-engine/src/main/java/org/zanata/magpie/backend/mock/MockTranslatorBackend.java
- mt-engine/src/main/java/org/zanata/magpie/util/DTOUtil.java
- mt-engine/src/test/java/org/zanata/magpie/backend/mock/MockTranslatorBackendTest.java
- pom.xml
- rebuild.sh
- server/pom.xml
- server/src/main/java/org/zanata/magpie/action/FrontendAssets.java
- server/src/main/java/org/zanata/magpie/action/FrontendManifest.java
- server/src/main/java/org/zanata/magpie/service/ConfigurationService.java
- server/src/test/java/org/zanata/magpie/service/ConfigurationServiceTest.java
- server/src/test/java/org/zanata/magpie/service/MTStartupTest.java
- option to enable dev mode (even when real backend is enabled)
- remove duplicated/unneeded dependency (our code base to use jackson 2, google uses jackson 1)
- upgrade google cloud client version
> General maintenance 

- business-svc/src/main/java/org/zanata/magpie/service/DocumentContentTranslatorService.java
- business-svc/src/main/java/org/zanata/magpie/util/ArticleUtil.java
- server/src/test/java/org/zanata/magpie/util/ArticleUtilTest.java
https://zanata.atlassian.net/browse/ZNTAMT-31
> fix: fix IndexOutOfBoundException

- server/src/main/webapp/WEB-INF/liquibase
> feat(liquibase): liquibase script

- common/src/main/java/org/zanata/magpie/api/dto/LocaleCode.java
- common/src/main/java/org/zanata/magpie/api/service/DocumentResource.java
- common/src/test/java/org/zanata/magpie/api/dto/LocaleCodeTest.java
- mt-data/src/main/java/org/zanata/magpie/dao/LocaleDAO.java
- mt-engine/src/main/java/org/zanata/magpie/backend/ms/MicrosoftTranslatorBackend.java
- server/src/main/java/org/zanata/magpie/api/service/impl/DocumentResourceImpl.java
- server/src/test/java/org/zanata/magpie/api/service/DocumentResourceImplTest.java
https://zanata.atlassian.net/browse/ZNTAMT-42
> feat(ZNTAMT-42): try locale without country code

- server/src/test/java/org/zanata/magpie/event/AccountCreatedTest.java
add in new test to increase coverage
> test: increase test coverage

- mt-data/src/main/resources/db/changelogs/db.changelog-1.1.xml
Update username and passwordhash constraint in account table
Note: need to try out with an existing database which contains a user in credential table.
> update changelog to fix account constraint

- business-svc/pom.xml
- business-svc/src/main/java/org/zanata/magpie/service/PersistentTranslationService.java
https://zanata.atlassian.net/browse/ZNTAMT-54
> fix(ZNTAMT-54): avoid need for psql on classpath

- business-svc/src/main/java/org/zanata/magpie/service/PersistentTranslationService.java
- common/src/main/java/org/zanata/magpie/service/TranslatorBackend.java
- mt-engine/src/main/java/org/zanata/magpie/backend/google/GoogleTranslatorBackend.java
https://zanata.atlassian.net/browse/ZNTAMT-56
> fix(ZNTAMT-56): avoid Dependent scope for GoogleTranslatorBackend

- mt-data/src/main/resources/META-INF/persistence.xml
- pom.xml
- server/Dockerfile
- server/src/main/java/org/zanata/magpie/filter/PoFileAdapter.java
Introduced some changes for ignoring NPE on file upload feature and postgres dependencies.
> Postgres upgrade and NPE on file upload fix
